server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true