server:
  port: 8084

spring:
  application:
    name: RECRUITER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/recruiter-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true