#PORT NUMBER
server:
  port: 8082

# APPLICATION NAME
spring:
  application:
    name: RESUME-SERVICE

# DATABASE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/resume-db
    username: root
    password: root

# TABLE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql: true

    show-sql: true

#  FILE UPLOAD CONFIGURATION
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


# ACTUATOR CONFIGURATION
#  To Enable the health check and other endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

# Log Level Configuration
logging:
    level:
      root: INFO
      com.resume.screening: DEBUG


# Resume Directories for Uploads
file:
    upload-dir: ./resumes